version: "3.9"

volumes:
  postgres_data:

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .db.env
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER:-postgres}"]
      interval: 1s
      timeout: 5s
      retries: 10
  auth:
    build: ./services/auth/
    volumes:
      - ./services/auth/:/opt/
    entrypoint: uvicorn base.main:app --host 0.0.0.0 --port 8001 --reload
    env_file:
      - .auth.env
    depends_on:
      - db
      - migrations
  migrations:
    build: ./services/auth/
    volumes:
      - ./services/auth/:/opt/
    entrypoint: ./migrationsscript.sh
    env_file:
      - .auth.env
    depends_on:
      db:
        condition: service_healthy
  nginx:
    build: ./services/nginx/
    ports:
      - "8000:80"
    depends_on:
      - auth
