version: "3.9"

services:
  api:
    build: ./services/api/
    volumes:
      - ./services/api/:/opt/
    entrypoint: uvicorn main:app --host 0.0.0.0 --port 8001 --reload
  nginx:
    build: ./services/nginx/
    ports:
      - "8000:80"
    depends_on:
      - api
