"""empty message

Revision ID: 08196f522517
Revises:
Create Date: 2022-09-25 14:05:38.065906

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '08196f522517'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userprofile',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(length=30), nullable=True),
                    sa.Column('email', sa.String(length=30), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('role', sa.Enum('admin', 'moderator', 'viewer', name='roleenum'), nullable=True),
                    sa.Column('password', sa.String(length=72), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    op.create_table('userrefreshtokens',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('refresh_token', sa.String(length=150), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['userprofile.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('usersecurity',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('access_token', sa.String(length=150), nullable=True),
                    sa.Column('secondary_token', sa.String(length=150), nullable=True),
                    sa.Column('email_sent_time', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['id'], ['userprofile.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usersecurity')
    op.drop_table('userrefreshtokens')
    op.drop_table('userprofile')
    # ### end Alembic commands ###
