"""empty message

Revision ID: 4f6148938b8b
Revises: 9f8418b5620e
Create Date: 2022-09-03 11:14:31.684709

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4f6148938b8b'
down_revision = '9f8418b5620e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_refresh_tokens',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('refresh_token', sa.String(length=150), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_refresh_tokens')
    # ### end Alembic commands ###
