"""empty message

Revision ID: 7f7609356bd7
Revises:
Create Date: 2022-09-24 17:00:49.859369

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '7f7609356bd7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actor',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('content',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=50), nullable=False),
                    sa.Column('description', sa.String(length=500), nullable=False),
                    sa.Column('year', sa.Integer(), nullable=False),
                    sa.Column('release_date', sa.DateTime(), nullable=True),
                    sa.Column('age_limit', sa.Integer(), nullable=False),
                    sa.Column('poster', sa.String(length=100), nullable=False),
                    sa.Column('background', sa.String(length=100), nullable=False),
                    sa.Column('imdb_rating', sa.Float(), nullable=True),
                    sa.Column('imdb_vote_count', sa.Integer(), nullable=True),
                    sa.Column('kinopoisk_rating', sa.Float(), nullable=True),
                    sa.Column('kinopoisk_vote_count', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('country',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=False),
                    sa.Column('abbr', sa.String(length=5), nullable=False),
                    sa.Column('code', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('director',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('genre',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('media',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=50), nullable=False),
                    sa.Column('source', sa.String(length=100), nullable=False),
                    sa.Column('preview', sa.String(length=100), nullable=True),
                    sa.Column('duration', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('contentactors',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('actor_id', sa.Integer(), nullable=True),
                    sa.Column('content_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['actor_id'], ['actor.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('contentcountries',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('country_id', sa.Integer(), nullable=True),
                    sa.Column('content_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ),
                    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('contentdirectors',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('director_id', sa.Integer(), nullable=True),
                    sa.Column('content_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ),
                    sa.ForeignKeyConstraint(['director_id'], ['director.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('contentgenres',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('genre_id', sa.Integer(), nullable=True),
                    sa.Column('content_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ),
                    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('movie',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('content_id', sa.Integer(), nullable=True),
                    sa.Column('media_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ),
                    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('serial',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('content_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('season',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('serial_id', sa.Integer(), nullable=True),
                    sa.Column('content_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ),
                    sa.ForeignKeyConstraint(['serial_id'], ['serial.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('episode',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('season_id', sa.Integer(), nullable=True),
                    sa.Column('content_id', sa.Integer(), nullable=True),
                    sa.Column('media_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ),
                    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
                    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('episode')
    op.drop_table('season')
    op.drop_table('serial')
    op.drop_table('movie')
    op.drop_table('contentgenres')
    op.drop_table('contentdirectors')
    op.drop_table('contentcountries')
    op.drop_table('contentactors')
    op.drop_table('media')
    op.drop_table('genre')
    op.drop_table('director')
    op.drop_table('country')
    op.drop_table('content')
    op.drop_table('actor')
    # ### end Alembic commands ###
