"""empty message

Revision ID: 46e92ad8d672
Revises: 7f7609356bd7
Create Date: 2022-11-13 07:33:00.862609

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '46e92ad8d672'
down_revision = '7f7609356bd7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userlibrary',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('object_type', sa.Unicode(length=255), nullable=False),
                    sa.Column('object_id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column(
                        'list_type',
                        sa.Enum(
                            'favorite',
                            'watch_later',
                            'watched',
                            'history',
                            name='librarytypeenum'),
                        nullable=False),
                    sa.Column('offset', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userlibrary')
    # ### end Alembic commands ###
