"""empty message

Revision ID: af96d8f5c0a0
Revises: 2d6df7390d56
Create Date: 2022-11-13 08:17:14.920094

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'af96d8f5c0a0'
down_revision = '2d6df7390d56'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'episode',
        sa.Column(
            'content_type',
            sa.Enum(
                'movie',
                'serial',
                'season',
                'episode',
                'moment',
                name='mediacontenttypeenum'),
            nullable=True))
    op.add_column(
        'movie',
        sa.Column(
            'content_type',
            sa.Enum(
                'movie',
                'serial',
                'season',
                'episode',
                'moment',
                name='mediacontenttypeenum'),
            nullable=True))
    op.add_column(
        'season',
        sa.Column(
            'content_type',
            sa.Enum(
                'movie',
                'serial',
                'season',
                'episode',
                'moment',
                name='mediacontenttypeenum'),
            nullable=True))
    op.add_column(
        'serial',
        sa.Column(
            'content_type',
            sa.Enum(
                'movie',
                'serial',
                'season',
                'episode',
                'moment',
                name='mediacontenttypeenum'),
            nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('serial', 'content_type')
    op.drop_column('season', 'content_type')
    op.drop_column('movie', 'content_type')
    op.drop_column('episode', 'content_type')
    # ### end Alembic commands ###
