"""empty message

Revision ID: 60f1c42d5512
Revises: e6c9eb0e87a0
Create Date: 2022-11-19 15:09:57.273170

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '60f1c42d5512'
down_revision = 'e6c9eb0e87a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('userlibrary', column_name='list_type', new_column_name='library_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('userlibrary', column_name='library_type', new_column_name='list_type')
    # ### end Alembic commands ###
