"""empty message

Revision ID: 42566682af96
Revises: 60f1c42d5512
Create Date: 2022-12-03 10:22:46.801174

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '42566682af96'
down_revision = '60f1c42d5512'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('content', 'description',
                    existing_type=sa.VARCHAR(length=500),
                    type_=sa.String(length=1000),
                    existing_nullable=False)
    op.alter_column('content', 'poster',
                    existing_type=sa.VARCHAR(length=100),
                    type_=sa.String(length=200),
                    existing_nullable=False)
    op.alter_column('content', 'background',
                    existing_type=sa.VARCHAR(length=100),
                    type_=sa.String(length=200),
                    existing_nullable=False)
    op.alter_column('media', 'source',
                    existing_type=sa.VARCHAR(length=100),
                    type_=sa.String(length=200),
                    existing_nullable=False)
    op.alter_column('media', 'preview',
                    existing_type=sa.VARCHAR(length=100),
                    type_=sa.String(length=200),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media', 'preview',
                    existing_type=sa.String(length=200),
                    type_=sa.VARCHAR(length=100),
                    existing_nullable=True)
    op.alter_column('media', 'source',
                    existing_type=sa.String(length=200),
                    type_=sa.VARCHAR(length=100),
                    existing_nullable=False)
    op.alter_column('content', 'background',
                    existing_type=sa.String(length=200),
                    type_=sa.VARCHAR(length=100),
                    existing_nullable=False)
    op.alter_column('content', 'poster',
                    existing_type=sa.String(length=200),
                    type_=sa.VARCHAR(length=100),
                    existing_nullable=False)
    op.alter_column('content', 'description',
                    existing_type=sa.String(length=1000),
                    type_=sa.VARCHAR(length=500),
                    existing_nullable=False)
    # ### end Alembic commands ###
