"""empty message

Revision ID: e6c9eb0e87a0
Revises: af96d8f5c0a0
Create Date: 2022-11-13 08:50:19.588785

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e6c9eb0e87a0'
down_revision = 'af96d8f5c0a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('userlibrary_object_type_object_id_user_id_key', 'userlibrary', type_='unique')
    op.create_unique_constraint(None, 'userlibrary', ['object_type', 'object_id', 'user_id', 'list_type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userlibrary', type_='unique')
    op.create_unique_constraint('userlibrary_object_type_object_id_user_id_key',
                                'userlibrary', ['object_type', 'object_id', 'user_id'])
    # ### end Alembic commands ###
