"""empty message

Revision ID: b3a967b95266
Revises: bd708baa5a0c
Create Date: 2023-02-27 19:44:43.323870

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b3a967b95266'
down_revision = 'bd708baa5a0c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('contentactors_content_id_fkey', 'contentactors', type_='foreignkey')
    op.create_foreign_key(None, 'contentactors', 'content', ['content_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('contentcountries_content_id_fkey', 'contentcountries', type_='foreignkey')
    op.create_foreign_key(None, 'contentcountries', 'content', ['content_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('contentdirectors_content_id_fkey', 'contentdirectors', type_='foreignkey')
    op.create_foreign_key(None, 'contentdirectors', 'content', ['content_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('contentgenres_content_id_fkey', 'contentgenres', type_='foreignkey')
    op.create_foreign_key(None, 'contentgenres', 'content', ['content_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('episode_media_id_fkey', 'episode', type_='foreignkey')
    op.drop_constraint('episode_content_id_fkey', 'episode', type_='foreignkey')
    op.create_foreign_key(None, 'episode', 'media', ['media_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'episode', 'content', ['content_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('movie_content_id_fkey', 'movie', type_='foreignkey')
    op.drop_constraint('movie_media_id_fkey', 'movie', type_='foreignkey')
    op.create_foreign_key(None, 'movie', 'content', ['content_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'movie', 'media', ['media_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('season_content_id_fkey', 'season', type_='foreignkey')
    op.create_foreign_key(None, 'season', 'content', ['content_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('serial_content_id_fkey', 'serial', type_='foreignkey')
    op.create_foreign_key(None, 'serial', 'content', ['content_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'serial', type_='foreignkey')
    op.create_foreign_key('serial_content_id_fkey', 'serial', 'content', ['content_id'], ['id'])
    op.drop_constraint(None, 'season', type_='foreignkey')
    op.create_foreign_key('season_content_id_fkey', 'season', 'content', ['content_id'], ['id'])
    op.drop_constraint(None, 'movie', type_='foreignkey')
    op.drop_constraint(None, 'movie', type_='foreignkey')
    op.create_foreign_key('movie_media_id_fkey', 'movie', 'media', ['media_id'], ['id'])
    op.create_foreign_key('movie_content_id_fkey', 'movie', 'content', ['content_id'], ['id'])
    op.drop_constraint(None, 'episode', type_='foreignkey')
    op.drop_constraint(None, 'episode', type_='foreignkey')
    op.create_foreign_key('episode_content_id_fkey', 'episode', 'content', ['content_id'], ['id'])
    op.create_foreign_key('episode_media_id_fkey', 'episode', 'media', ['media_id'], ['id'])
    op.drop_constraint(None, 'contentgenres', type_='foreignkey')
    op.create_foreign_key('contentgenres_content_id_fkey', 'contentgenres', 'content', ['content_id'], ['id'])
    op.drop_constraint(None, 'contentdirectors', type_='foreignkey')
    op.create_foreign_key('contentdirectors_content_id_fkey', 'contentdirectors', 'content', ['content_id'], ['id'])
    op.drop_constraint(None, 'contentcountries', type_='foreignkey')
    op.create_foreign_key('contentcountries_content_id_fkey', 'contentcountries', 'content', ['content_id'], ['id'])
    op.drop_constraint(None, 'contentactors', type_='foreignkey')
    op.create_foreign_key('contentactors_content_id_fkey', 'contentactors', 'content', ['content_id'], ['id'])
    # ### end Alembic commands ###
