"""empty message

Revision ID: f8d142040ed0
Revises: b3a967b95266
Create Date: 2023-04-09 08:20:23.998474

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f8d142040ed0'
down_revision = 'b3a967b95266'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contentactors', 'actor_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('contentactors', 'content_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('contentcountries', 'country_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('contentcountries', 'content_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('contentdirectors', 'director_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('contentdirectors', 'content_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('contentgenres', 'genre_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('contentgenres', 'content_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('episode', 'season_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('episode', 'content_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('episode', 'media_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('movie', 'content_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('movie', 'media_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('playlistitem', 'playlist_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('season', 'serial_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('season', 'content_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('serial', 'content_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('serial', 'content_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('season', 'content_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('season', 'serial_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('playlistitem', 'playlist_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('movie', 'media_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('movie', 'content_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('episode', 'media_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('episode', 'content_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('episode', 'season_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('contentgenres', 'content_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('contentgenres', 'genre_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('contentdirectors', 'content_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('contentdirectors', 'director_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('contentcountries', 'content_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('contentcountries', 'country_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('contentactors', 'content_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('contentactors', 'actor_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    # ### end Alembic commands ###
