# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authorization.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x61uthorization.proto\x12\rauthorization\",\n\x14\x41uthorizationRequest\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\"/\n\x15\x41uthorizationResponse\x12\x0f\n\x02id\x18\x01 \x01(\x04H\x00\x88\x01\x01\x42\x05\n\x03_id2g\n\rAuthorization\x12V\n\tauthorize\x12#.authorization.AuthorizationRequest\x1a$.authorization.AuthorizationResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'authorization_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _AUTHORIZATIONREQUEST._serialized_start = 38
    _AUTHORIZATIONREQUEST._serialized_end = 82
    _AUTHORIZATIONRESPONSE._serialized_start = 84
    _AUTHORIZATIONRESPONSE._serialized_end = 131
    _AUTHORIZATION._serialized_start = 133
    _AUTHORIZATION._serialized_end = 236
# @@protoc_insertion_point(module_scope)
