"""empty message

Revision ID: 49b87efdc0c5
Revises:
Create Date: 2022-06-17 07:04:06.288603

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '49b87efdc0c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
