"""empty message

Revision ID: e2f544bb510b
Revises:
Create Date: 2022-07-26 06:47:52.859133

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e2f544bb510b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profile',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(length=30), nullable=True),
                    sa.Column('email', sa.String(length=30), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('role', sa.Enum('admin', 'moderator', 'viewer', name='roleenum'), nullable=True),
                    sa.Column('password', sa.String(length=72), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    op.create_table('user_security',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('access_token', sa.String(length=150), nullable=True),
                    sa.Column('secondary_token', sa.String(length=150), nullable=True),
                    sa.Column('email_sent_time', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['id'], ['user_profile.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_security')
    op.drop_table('user_profile')
    # ### end Alembic commands ###
